import type { Category, Medicine, Sale, Supplier } from "@/types";

/**
 * Placeholder data so the screens render before the API exists.
 * Replace these with real fetches — the shapes already match the Zod schemas.
 */

const daysFromNow = (days: number) =>
  new Date(Date.now() + days * 86_400_000);

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "MedSource Distributors",
    contactPerson: "Rina Patel",
    email: "orders@medsource.example",
    phone: "+1 555 0142",
    address: "18 Harbour Road, Springfield",
    licenseNumber: "DL-99231",
    isActive: true,
    createdAt: new Date("2024-02-11"),
  },
  {
    id: "sup-2",
    name: "Vitalis Pharma",
    contactPerson: "Omar Haddad",
    email: "supply@vitalis.example",
    phone: "+1 555 0177",
    address: "402 Industrial Park",
    licenseNumber: "DL-77410",
    isActive: true,
    createdAt: new Date("2024-06-03"),
  },
  {
    id: "sup-3",
    name: "Northline Medical",
    contactPerson: "Ellen Cho",
    email: "hello@northline.example",
    phone: "+1 555 0198",
    address: "7 Kestrel Avenue",
    licenseNumber: "DL-51286",
    isActive: false,
    createdAt: new Date("2023-11-20"),
  },
];

export const categories: Category[] = [
  { id: "cat-1", name: "Antibiotics", description: "Bacterial infection treatment", medicineCount: 24 },
  { id: "cat-2", name: "Analgesics", description: "Pain relief", medicineCount: 31 },
  { id: "cat-3", name: "Cardiovascular", description: "Heart and blood pressure", medicineCount: 18 },
  { id: "cat-4", name: "Respiratory", description: "Asthma and allergy", medicineCount: 12 },
  { id: "cat-5", name: "Vitamins", description: "Supplements", medicineCount: 27 },
];

export const medicines: Medicine[] = [
  {
    id: "med-1",
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin",
    brand: "Amoxil",
    categoryId: "cat-1",
    supplierId: "sup-1",
    dosageForm: "capsule",
    strength: "500mg",
    barcode: "8901234567",
    batchNumber: "BT-2201",
    costPrice: 4.2,
    sellingPrice: 6.5,
    quantity: 240,
    reorderLevel: 50,
    expiryDate: daysFromNow(420),
    prescriptionRequired: true,
    notes: "",
    createdAt: new Date("2025-01-12"),
    updatedAt: new Date("2025-06-02"),
  },
  {
    id: "med-2",
    name: "Paracetamol 650mg",
    genericName: "Acetaminophen",
    brand: "Calpol",
    categoryId: "cat-2",
    supplierId: "sup-2",
    dosageForm: "tablet",
    strength: "650mg",
    barcode: "8901234568",
    batchNumber: "BT-3310",
    costPrice: 1.1,
    sellingPrice: 2.0,
    quantity: 32,
    reorderLevel: 80,
    expiryDate: daysFromNow(210),
    prescriptionRequired: false,
    notes: "",
    createdAt: new Date("2025-02-08"),
    updatedAt: new Date("2025-07-19"),
  },
  {
    id: "med-3",
    name: "Atorvastatin 20mg",
    genericName: "Atorvastatin",
    brand: "Lipitor",
    categoryId: "cat-3",
    supplierId: "sup-1",
    dosageForm: "tablet",
    strength: "20mg",
    barcode: "8901234569",
    batchNumber: "BT-1180",
    costPrice: 7.4,
    sellingPrice: 11.25,
    quantity: 0,
    reorderLevel: 40,
    expiryDate: daysFromNow(95),
    prescriptionRequired: true,
    notes: "Awaiting restock from supplier",
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-08-01"),
  },
  {
    id: "med-4",
    name: "Salbutamol Inhaler",
    genericName: "Salbutamol",
    brand: "Ventolin",
    categoryId: "cat-4",
    supplierId: "sup-2",
    dosageForm: "inhaler",
    strength: "100mcg",
    barcode: "8901234570",
    batchNumber: "BT-4402",
    costPrice: 9.8,
    sellingPrice: 14.0,
    quantity: 64,
    reorderLevel: 25,
    expiryDate: daysFromNow(24),
    prescriptionRequired: true,
    notes: "",
    createdAt: new Date("2025-03-22"),
    updatedAt: new Date("2025-07-30"),
  },
  {
    id: "med-5",
    name: "Vitamin D3 1000IU",
    genericName: "Cholecalciferol",
    brand: "SunVit",
    categoryId: "cat-5",
    supplierId: "sup-3",
    dosageForm: "tablet",
    strength: "1000IU",
    barcode: "8901234571",
    batchNumber: "BT-5521",
    costPrice: 3.0,
    sellingPrice: 5.75,
    quantity: 180,
    reorderLevel: 60,
    expiryDate: daysFromNow(-12),
    prescriptionRequired: false,
    notes: "Quarantine — past expiry",
    createdAt: new Date("2024-09-14"),
    updatedAt: new Date("2025-05-11"),
  },
];

export const sales: Sale[] = [
  {
    id: "sale-1",
    invoiceNumber: "INV-10241",
    customerName: "Walk-in",
    customerPhone: "",
    prescriptionRef: "RX-8891",
    paymentMethod: "cash",
    items: [{ medicineId: "med-1", quantity: 2, unitPrice: 6.5, discount: 0 }],
    taxRate: 5,
    subtotal: 13,
    tax: 0.65,
    total: 13.65,
    createdAt: new Date("2025-08-16T09:24:00"),
  },
  {
    id: "sale-2",
    invoiceNumber: "INV-10242",
    customerName: "Dana Whitfield",
    customerPhone: "+1 555 0110",
    prescriptionRef: "",
    paymentMethod: "card",
    items: [{ medicineId: "med-2", quantity: 4, unitPrice: 2.0, discount: 0.5 }],
    taxRate: 5,
    subtotal: 7.5,
    tax: 0.38,
    total: 7.88,
    createdAt: new Date("2025-08-16T11:02:00"),
  },
  {
    id: "sale-3",
    invoiceNumber: "INV-10243",
    customerName: "Marcus Bell",
    customerPhone: "+1 555 0166",
    prescriptionRef: "RX-8902",
    paymentMethod: "insurance",
    items: [{ medicineId: "med-4", quantity: 1, unitPrice: 14.0, discount: 2.0 }],
    taxRate: 5,
    subtotal: 12,
    tax: 0.6,
    total: 12.6,
    createdAt: new Date("2025-08-17T08:41:00"),
  },
];

export const findCategory = (id: string) => categories.find((c) => c.id === id);
export const findSupplier = (id: string) => suppliers.find((s) => s.id === id);
export const findMedicine = (id: string) => medicines.find((m) => m.id === id);
